import { PERMISSIONS } from './permissions';

export const ROLES = {
  SUPER_ADMIN: [
    PERMISSIONS.MANAGE_COMPANY,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_JOBS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_FINANCE
  ],
  COMPANY_ADMIN: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_JOBS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.MANAGE_FINANCE
  ],
  TECHNICIAN: [
    PERMISSIONS.MANAGE_JOBS
  ]
};
